### ISSUE TITLE
Brainstorm correct ways to include PySpark & Delta dependencies in pyproject.toml file

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/mack#48]
Users have to supply a correct combination of Spark & Delta Lake versions for their setup to work, see [the compatibility matrix](https://docs.delta.io/latest/releases.html).

Mack depends on PySpark & Delta Lake.  We want Mack to work with a variety of Spark & Delta Lake combinations.

Here's how the dependencies are currently specified in the `pyproject.toml` file:

```toml
[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pre-commit = "^2.20.0"
pyspark = "3.3.1"
delta-spark = "2.1.1"
pytest = "7.2.0"
chispa = "0.9.2"
pytest-describe = "^1.0.0"
```

I'm not sure the best way to specify dependencies using Poetry to give our users the best Mack download experience.  Thoughts?
