### ISSUE TITLE
 Validate pre-commit config for pytest

### ISSUE THREAD

**Issue by cs23andris** [MrPowers/mack#96]
This is the current setup for pytest in the .yaml file
```
  - repo: local
    hooks:
    - id: pytest
      name: pytest
      entry: pytest tests/
      pass_filenames: false
      language: system
```

To leverage the development environment setup by poetry for for this hook then the entry key should be updated: `poetry run pytest` instead of `pytest tests/`.
